name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15  

    - name: Install Python and dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip
        pip install localstack

    - name: Start localstack
      run: localstack start

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve

    - name: Terraform destroy (cleanup)
      run: terraform destroy -auto-approve
